# Generated by Django 3.2.5 on 2021-07-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
